#!/usr/bin/env bash
diff_js_files=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.jsx" | tr '\n' ' ')

if [[ ! -z $diff_js_files ]]; then
    echo $diff_js_files
    # Prettify all staged .js files
    echo "$diff_js_files" | xargs ./node_modules/.bin/prettier --write
    # Add back the modified/prettified files to staging
    echo "$diff_js_files" | xargs git add
fi
